name: 'Spendr Continuous Deployment'

on:
  push:
    branches: ['ci-cd-configurations']
  pull_request:
    branches: ['ci-cd-configurations']

jobs:
  build-server:
    name: 'spendr server continuous deployment build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install Dependencies
      run: cd server && npm install

    - name: Build Server
      run: cd server && npm run build

    - name: Upload production ready build files
      uses: actions/upload-artifact@v3
      with:
        name: spendr-server-static
        path: ./server/build

  build-client:
    name: 'spendr client continuous deployment build'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install Dependencies
      run: cd client && npm install

    - name: Build Client
      run: cd client && npm run build

    - name: Upload production ready build files
      uses: actions/upload-artifact@v2
      with:
        name: spendr-client-static
        path: ./client/build

  publish-to-docker-server:
    name: 'spendr server continuous deployment - publish'
    needs: build-server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci-cd-configurations'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: spendr-server-static
        path: ./server/build

    - name: Log on to docker hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: BarbzCodez/Spendr

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./.docker/server/Dockerfile
        context: ./server
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
  publish-to-docker-client:
    name: 'spendr client continuous deployment - publish'
    needs: build-client
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci-cd-configurations'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: spendr-client-static
        path: ./client/build

    - name: Log on to docker hub
      run: |
        export username=$(echo ${{ secrets.DOCKER_USERNAME }} | sed '"')
        echo $username
      run: |
        export password=$(echo ${{ secrets.DOCKER_USERNAME }} | sed '"')
        echo $password
      uses: docker/login-action@v1 
      with:
        username: $username
        password: $password

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: BarbzCodez/Spendr

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./.docker/client/Dockerfile
        context: ./client
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}