name: SonarCloud analysis

on:
  push:
    branches: [ "sonarcloud-fix" ]
  pull_request:
    branches: [ "sonarcloud-fix" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze with SonarCloud

        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=BarbzCodez_Spendr
            -Dsonar.organization=spendr