name: 'Spendr Continuous Integration'

on:
  push:
    branches: ['ci-cd-configurations']
  pull_request:
    branches: ['ci-cd-configurations']

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd server
        npm install
        npm run build

  test-server:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        npm test
        npm run lint

  build-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd client
        npm install
        npm start

