name: 'Spendr Continuous Integration'

on:
  push:
    branches: ['ci-cd-configurations']
  pull_request:
    branches: ['ci-cd-configurations']

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd server
        npm install
        npm run build
        npm test
        npm run lint

  publish-to-docker:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Log on to docker hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: BarbzCodez/Spendr

    - name: Build and push
        uses: docker/build-push-action@v2
        file: ./.docker/server/Dockerfile
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



    